# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodereal-app:
  ownerLabels:
    team: "enhanced-api"
    biz: "${qanet_name}"
    appcom: "gold-digger"
  karpenter:
    enabled: true
    consolidation: "off"
  podDisruptionBudget:
    enabled: false
    maxUnavailable: 1
  serviceMonitor:
    enabled: true
    monitorPath: /debug/metrics/prometheus
  serviceAccount:
    create: true
    name: gold-digger
  replicaCount: 1
  podAnnotations:
    reloader.stakater.com/auto: "true"
  image:
    repository: 553885929720.dkr.ecr.us-east-1.amazonaws.com/gold-digger-v2
    pullPolicy: Always
    tag: ${enhanced_tag}
  resources:
    limits:
      cpu: 12
      memory: 25Gi
    requests:
      cpu: 1
      memory: 10Gi
  service:
    type: ClusterIP
    ports:
      - port: 9090
        protocol: TCP
        targetPort: 9090
        name: metrics
  configMapsMountPath: "/opt/app/configs"
  containers:
    # command: ["/bin/sh"]
    # args: ["-c", "while true;do sleep 3000000000000000;done"]
    # logsMountPath: "/opt/app/logs/"
    env:
      - name: PROFILE
        value: prod
      - name: NODE_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.hostIP
  logVolume: {}
  configMaps:
    config.toml:
      data:
        config.toml: |-
          [Store]
          DSN = "bijieprd:m(*w-NdSi&NH7oZUktaBQ6nfp3QDmgpy@tcp(tf-nodereal-qa-bsc-l2-opt-chaindb.cluster-cb6vaj1ctcqk.us-east-1.rds.amazonaws.com:3306)/${db_name}?parseTime=true&multiStatements=true&interpolateParams=true"
          
          [ReadStore]
          DSN = "bijieprd:m(*w-NdSi&NH7oZUktaBQ6nfp3QDmgpy@tcp(tf-nodereal-qa-bsc-l2-opt-chaindb.cluster-ro-cb6vaj1ctcqk.us-east-1.rds.amazonaws.com:3306)/${db_name}?parseTime=true&multiStatements=true&interpolateParams=true"
          
          [Debug]
          ListenAddr = ":9090"
          
          [Log]
          RootDir = "./logs"
          Level = "info"
          
          [L2CrossConfig]
          DepositAttributeAccountAddress = "0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001"
          DepositAttributeContractAddress = "0x4200000000000000000000000000000000000015"
          DepositContractAddress = "${optimism_portal_proxy}"
          WithDrawContractAddress = "0x4200000000000000000000000000000000000016"
          L2CrossDomainMessengerAddress = "0x4200000000000000000000000000000000000007"
          
          [L1TransferConfig]
          StateBatchContractAddress = "${l2_output_oracle_proxy}"
          OptimismPortalAddress = "${optimism_portal_proxy}"
          FinalizeMethodID = "0x8c3152e9"
          ProveMethodID = "0x4870496f"

          [[ChainFeeds]]
          ChainName="${qanet_name}"
          CacheDepth=128
          ReorgDepth=64
          Default=true
          Enable=true
          RPCEndpoint = [
            "https://${qanet_name}-seq-0.bk.nodereal.cc",
          ]
          SpecialGetBlockReceiptMethod="eth_getBlockReceipts"
          [[ChainFeeds.RateLimits]]
          Method="eth_getBlockByNumber"
          Rate=200
          Size=200
          [[ChainFeeds.RateLimits]]
          Method="eth_getTransactionReceipt"
          Rate=250
          Size=250
          
          [[ChainFeeds]]
          ChainName="l1-qa-net"
          CacheDepth=128
          ReorgDepth=64
          Default=false
          Enable=true
          RPCEndpoint = [
            "${l1_rpc_url}",
          ]
          SpecialGetBlockReceiptMethod="eth_getBlockReceipts"
          [[ChainFeeds.RateLimits]]
          Method="eth_getBlockByNumber"
          Rate=200
          Size=200
          [[ChainFeeds.RateLimits]]
          Method="eth_getTransactionReceipt"
          Rate=250
          Size=250

          [[Tasks]]
          Enable=1
          Name="external_transfer"
          MaxConn=2
          LatestBlockNumber=0
          StartBlockNumber=340000
          IsRealTimeTask="Y"
          
          
          

          



